import differential_geometry_immersions_minimal_prescribed_foundation_canonical_lane_mathlib.GateLemmas
import differential_geometry_immersions_minimal_prescribed_foundation_canonical_lane_mathlib.FinalTheorem
